general {
    # No gaps between windows or borders
    	gaps_in = 5
    	gaps_out = 5
    # border_size = 3

    # Change to niri-like side-scrolling layout
    # layout = scrolling
}


decoration {
    # Use round window corners
    rounding = 8

    # Dim unfocused windows (0.0 = no dim, 1.0 = fully dimmed)
    # dim_inactive = true
    # dim_strength = 0.15
}
