# All keystroke unbindings are here
# Custom/User Edited


# Unbind TAB between workspaces
# unbind = SUPER, TAB
# unbind = SUPER SHIFT, TAB

# Unbinding key combos for the uninstalled apps

# Unbind Music (Spotify)
unbind = SUPER SHIFT, M

# Unbind Signal
unbind = SUPER SHIFT, G

# Unbind Obsidian
unbind = SUPER SHIFT, O

# Unbind Typora
unbind = SUPER SHIFT, W

# Unbind 1password
unbind = SUPER SHIFT, SLASH

# Unbinding Web apps
# Unbind Grok
unbind = SUPER SHIFT ALT, A

# Unbind Calendar (Hey App)
unbind = SUPER SHIFT, C

# Unbind Email (Hey App)
unbind = SUPER SHIFT, E

# Unbind Google Messages
unbind = SUPER SHIFT CTRL, G

# Unbind X.com
unbind = SUPER SHIFT, X

# Unbind X Post
unbind = SUPER SHIFT ALT, X
