animations{
    # Smooth bezier
bezier = mac, 0.22, 1, 0.36, 1

# Workspace animation
animation = workspaces, 1, 8, default, slide

# Window animations
animation = windows, 1, 6, mac, popin 85%
animation = border, 1, 8, default
animation = fade, 1, 6, default
  }
