# All custom keybindings are here


# TAB between workspaces
# bindd = SUPER, TAB, Next workspace, workspace, +1
# bindd = SUPER SHIFT, TAB, Previous workspace, workspace, -1
#
#
# Close Window
bindd = SUPER, Q, Close window, killactive

# Launch Mission Center
bindd = CTRL SHIFT, ESCAPE, Launch Mission Center, exec, missioncenter

# Launch YT Music WebApp #Override Spotify
bindd = SUPER SHIFT, M, YT Music, exec, omarchy-launch-webapp "https://music.youtube.com/"

# Launch Google Keep WebApp #Override Obsidian
bindd = SUPER SHIFT, O, Google Keep, exec, omarchy-launch-webapp "https://keep.google.com/"

# Launch Gmail WebApp #Override HeyMail
bindd = SUPER SHIFT, E, Gmail, exec, omarchy-launch-webapp "https://mail.google.com/"

# Launch Google Calendar WebApp #Override HeyCalendar 
bindd = SUPER SHIFT, C, Google Calendar, exec, omarchy-launch-webapp "https://calendar.google.com/"

# Launch Bitwarden Password Manager #Override 1password 
bindd = SUPER SHIFT, SLASH, Passwords, exec, uwsm-app -- bitwarden-desktop
